### ISSUE TITLE
TCK style tests

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#108]
Some of the test coverage in _betamax-proxy_ is equally applicable to the HTTPClient implementation. It would be a good idea to convert those tests into abstract TCK style tests that have implementations in both the _betamax-proxy_ and _betamax-httpclient_ modules.

These all look like candidates:
- AnnotationSpec
- AnnotationTest
- LocalhostSpec
- SmokeSpec
- BasicAuthSpec
- HttpsSpec
- IgnoreHostsSpec
- PreExistingProxySpec
- ProxyRecordAndPlaybackSpec
- ProxyTimeoutSpec

**Comment by cowboygneox** [comment]
Moving to Trello: https://trello.com/c/6ZS327rf.
