### ISSUE TITLE
Using BetamaxConfig.groovy and not specifying tapeRoot throws GroovyCastException

### ISSUE THREAD

**Issue by erdi** [betamaxteam/betamax#109]
in `configureFromConfig()` first line should probably be changed to `tapeRoot = config.betamax.tapeRoot ?: new File(DEFAULT_TAPE_ROOT)`

**Comment by cowboygneox** [comment]
I suspect this has been addressed in the 2.x refactor. Please let me know if it's still an issue. We have no plans to release another 1.2.x release at this time.

**Comment by cowboygneox** [comment]
@erdi Also, thank you very much for letting us know! Sorry for the latency, but we won't let it happen again.

**Comment by erdi** [comment]
Wow, that was some proper latency, @cowboygneox, over two years. Good to see that the project has a new maintainer!

**Comment by cowboygneox** [comment]
@erdi Life gets in the way sometimes, but now that @robfletcher and I have teamed up, it's less likely that it will get in the way of both of us simultaneously. I love this library, and I see a huge potential for greatness in the Java testing community, and I'm happy to contribute.

Feel free to say hi on our Gitter!
