### ISSUE TITLE
HTTPS CONNECT attempt is made even if playing back from tape

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#117]

**Comment by cowboygneox** [comment]
I dug into this a little today, and my initial impression is that littleproxy will probably need a patch. It doesn't offer an option for a `ClientToProxyConnection` to short out with a `CONNECT` request, but if we leverage `ClientToProxyConnection.java:473` in some way, it seems relatively easy to create the callback early and thus remove all of the responsibility from Betamax. In the near future, I will continue to investigate this fix.

**Comment by cowboygneox** [comment]
On second thought, it probably makes more sense for the `BetamaxFilters` to catch the `CONNECTED` and appropriately respond. The next request will be the _actual_ request, so we can then determine after that if the proxy actually has to hit the server (which it should do lazily/on demand), or play back an existing response.

**Comment by quiqua** [comment]
I'd like to help with that one, any hints on how to get started here with version 2? @cowboygneox

**Comment by cowboygneox** [comment]
@quiqua I'm not convinced this is actually an issue (still). Do you think it is?

**Comment by quiqua** [comment]
It's just a bit odd, that the a recorded tape still needs an internet connection.

**Comment by cowboygneox** [comment]
@quiqua I'm going to need a little time to investigate this again. I'll get back to you. I'll try to do it in the next day or two.
