### ISSUE TITLE
Replaying tapes against the server

### ISSUE THREAD

**Issue by lbovet** [betamaxteam/betamax#119]
Congrats for this nice project.
This is more a question than an issue:
Is it possible/planned to replay the tapes also against the server? It would be nice to benefit from the recording to also perform server tests. 
Maybe it could use/integrate a HttpUnit or a similar library.

**Comment by cowboygneox** [comment]
@lbovet How would we know to record without a request that instigates the conversation? I'm not sure how we could effectively manage opening a connection to listen for unprovoked server responses...
