### ISSUE TITLE
Feature Request: Tape Matching

### ISSUE THREAD

**Issue by dkowis** [betamaxteam/betamax#122]
In the context of a standalone proxy for testing, it'd be handy if I could use a request matcher to select the tape to use as well.

This way I could configure the proxy to use a tape per endpoint, or a tape per request type, or whatever crazy organization I would want to use.

Most of the matching logic would remain the same in the proxy, just how it selects the tape to use would be different.

This might be too difficult to do, as it'd require decoupling the recorder from the proxy, or setting up the proxy to use one of many recorders...

**Comment by cowboygneox** [comment]
@dkowis I don't think asking for a proxy composed of many recorders is asking for too much, though my initial feeling is concern over how we would do it in a way that would help create reliable tests. When replaying HTTP interactions, you almost certainly want them to be deterministic or else fail the test.

Do you think you can help me brainstorm and come up with acceptance criteria for this feature?

**Comment by dkowis** [comment]
It's been a long long time since I worked on this. I barely remember what I was doing at this stage. I think I wanted a way to make the tapes simpler so that I wouldn't have one giant tape with lots of requests in it, but instead a way to scope requests to tapes. Or maybe just a way to have multiple tapes to find data from, so that it's easier to examine/modify the tapes as necessary.

Glad to see some activity on betamax again :)

**Comment by cowboygneox** [comment]
@dkowis I can certainly see some use cases for tape composition that is done based on the scenario. I will have to devote some thought to it and see what comes out. You should do the same and let me know what you think.

**Comment by mirelon** [comment]
Imagine we have two scenarios:
1. Get data from endpoint A and then, according to the data, download something from endpoint C
2. Get data from endpoint B and then, according to the data, download something from endpoint C

As the logic of A and B is totally different and the only similarity is that they use C, it's reasonable to use two tapes - for A and B.

However, the requests on C are present in both tapes.

This issue would solve this duplicity by composing A test from tapes A and C and composing B test from tapes B and C.

**Comment by cowboygneox** [comment]
@mirelon It sounds like you're asking for just comparison of the response?

**Comment by mirelon** [comment]
@cowboygneox My usecase is using response of C as an additional data to complete usecase A, but I don't see how the case for just comparison of the response would be easier...
Both cases would benefit from using two tapes in the test.

**Comment by cowboygneox** [comment]
@mirelon When recording, how would we know what data to put where? Or would you just like the option to specify multiple tapes (that presumably have been doctored by hand)? If you just want the ability to combine multiple tapes together into one tape for runtime, that's a piece of cake.

**Comment by mirelon** [comment]
@cowboygneox For the start, combining two tapes together would be great. It would render all this things possible. In the write mode it could simply record to the first specified tape.
It would be then possible to manually take recorded interaction from the first tape and paste it to another tape.

For the future, each tape could be assigned a matchrule in order to automatically record to right tape.

**Comment by cowboygneox** [comment]
@mirelon So, as I understand it, we have two feature requests:

1. Allow multiple tapes to be specified and treat the tapes as one (and search for routes in order of tapes specified).
2. Allow the developer to provide some sort of match rule that would sort the requests into certain tapes.

How does that sound?

**Comment by mirelon** [comment]
@cowboygneox Great! I think the title of this thread corresponds to the second feature request.

**Comment by cowboygneox** [comment]
@mirelon https://github.com/betamaxteam/betamax/issues/198

**Comment by cowboygneox** [comment]
I could probably get to #198 soon. This one might take a bit more thought and nuance.
