### ISSUE TITLE
SNAPSHOT releases of 2.0.0?

### ISSUE THREAD

**Issue by dkowis** [betamaxteam/betamax#123]
How far away do you think this is? Just curious :)

**Comment by luisobo** [comment]
I'd would like a snapshot too. What is the most recent snapshot available anyway?

Thanks

**Comment by cowboygneox** [comment]
We're working on getting snapshots out this week, but they'll be super rough and a use at your own risk type of thing. If you plan on using them, I would advise communicating with us via Gitter so we can be in close contact while we make breaking changes.

**Comment by cowboygneox** [comment]
Ok, I lied, it might be early March since we're blocked on getting access, but trust me that SNAPSHOTs are our number 1 priority!

**Comment by cowboygneox** [comment]
Closing because we deployed 2.X. Sorry for the late closing...
