### ISSUE TITLE
bug: If tape name in yaml file doesn't match tape file name...

### ISSUE THREAD

**Issue by dkowis** [betamaxteam/betamax#124]
.... it writes all interactions to a different tape named by the name of the `name` field in the yaml file.

For example: Tape named "derpTape.yaml"

recorder.start("derpTape")

in the yaml file the name is "name: otherTape"

If interactions are not found, it'll write them all to a new file "otherTape.yaml"

**Comment by cowboygneox** [comment]
I don't think this is an issue in 2.x. Closing...
