### ISSUE TITLE
Content-Length header improvements during replay

### ISSUE THREAD

**Issue by dkowis** [betamaxteam/betamax#128]
It'd be really handy to have a configurable option to force re-calculation of the `Content-Length` header regardless of what it's set to in the tape. As I'm testing bodies, and mostly I just care about the content itself, not the gritty HTTP details, I'd like to be able to modify my body, or the headers, in the YAML file without having to manually re-calculate the size of the content.

On the other hand, if I'm wanting to test stuff where the content type header is blatantly wrong, to handle odd HTTP conditions, I should still be able to do this, but Betamax should warn me that it's going to do Bad Things<sup>TM</sup>

Because the symptom, at least with some clients, of not having a proper `Content-Length` header size set, when it is set too large for the modified body, the proxy appears to hang. Reference debugging in #126

**Comment by tonyghita** [comment]
I keep running into this issue in my tests. @dkowis did you ever find a solution?

**Comment by cowboygneox** [comment]
@dkowis This is actually a feature that I plan on implementing shortly for your exact reasons. `Content-Length` does not need to be a stored header for any reason, and should be calculated on the fly.

**Comment by dkowis** [comment]
It could be useful to override the content-length header so that its invalid if I wished to test things that way. I'd like for it to remain an option of sorts, along with printing the warning that "Hey your content length is invalid, but you told me to do this, so I'm doing it." Perhaps if it's left out of the recording it'll be automatically calculated, but if I put it into the recording it'll use the explicit amount, even if it doesn't match?

**Comment by cowboygneox** [comment]
@dkowis how does this sound:

1. Do not set `Content-Length` by default in the tape
2. If it is set explicitly (the tape was doctored) and the length does not match that of the payload, we log it as `INFO` or `WARN`.

Thoughts?

**Comment by cowboygneox** [comment]
Even just 2. would help a lot. It's tough as hell to debug an instance where `Content-Length` is not calculated correctly.

**Comment by dkowis** [comment]
:+1: Sounds good to me. By default you get sane behavior, and you have the opportunity to muck with the thing if you want to test bad behavior against your application easily. I like it.

**Comment by cowboygneox** [comment]
@dkowis Especially because if we obey the `Content-Length` specified by the original request, the recorded body payload can only be at most as long as specified. We probably should warn when the server specifies a `Content-Length` that we don't agree with.

**Comment by cowboygneox** [comment]
Managing this enhancement on Trello: https://trello.com/c/qlor2w70.
