### ISSUE TITLE
Tape is never used on CIs

### ISSUE THREAD

**Issue by paniko0** [betamaxteam/betamax#131]
Hi guys, I don't know what is happening or if it is a bug but my tests that uses Betamax never runs on CIs (Travis, CircleCI or Wercker). I also realized that Betamax is also failing on Travis (https://travis-ci.org/robfletcher/betamax).

There is a known bug about it? There is a closed issue about Travis #67 but I don't know if it's the same or if it is already in the current version.

**Comment by cowboygneox** [comment]
This is back on Travis-CI. It should be good to go.
