### ISSUE TITLE
Support a strict mode for SEQUENTIAL READ ONLY tapes that fail a test if all requests are not matched

### ISSUE THREAD

**Issue by tddmonkey** [betamaxteam/betamax#140]
I'm using Betamax for testing stateful endpoints and I need to ensure that my HTTP client sends the exact number of calls specified in my tape.  In order to support this I would need the test to fail if no. of requests made < no. of requests made.

**Comment by mirelon** [comment]
+1

**Comment by cowboygneox** [comment]
@tddmonkey This is a neat idea. If I understand correctly, you would like a feature that would verify that all interactions were used in a tape?

**Comment by tddmonkey** [comment]
That's correct.  I did an implementation back when I raised this but I'm not sure if I ever committed it anywhere.  I can try and dig it out if you like?

**Comment by cowboygneox** [comment]
@tddmonkey Please do. If nothing else, it'll help direct the acceptance criteria for the feature.

**Comment by cowboygneox** [comment]
Moving to Trello: https://trello.com/c/ToNAuzwv
