### ISSUE TITLE
next release date?

### ISSUE THREAD

**Issue by gesellix** [betamaxteam/betamax#150]
@robfletcher do you have plans when to release the next version? I would need the current code on master to make https proxying work. Thanks in advance!

**Comment by rschmitt** [comment]
Any updates on this?

**Comment by amedeiros** [comment]
Will there be a new release? Seems like HTTPS proxy does not work on the current release.

**Comment by bjhartin** [comment]
@robfletcher We're encountering some issues that I think have been fixed or for which you have pull requests.  Would be nice to have a release.

**Comment by mjallday** [comment]
@robfletcher this project still active?

**Comment by rompic** [comment]
+1

**Comment by yoghi** [comment]
+1

**Comment by cowboygneox** [comment]
This project is active again, and we have a release coming within the next month or two. I would expect snapshots sooner if you'd like a preview.

**Comment by gesellix** [comment]
oh yeah :wow: :-)
