### ISSUE TITLE
Please add a whitelist/blacklist for headers matcher

### ISSUE THREAD

**Issue by anovarini** [betamaxteam/betamax#154]
I'd like to have a way to select which of the headers I want to consider or ignore.

In particular, I found this issue related to the user agent.
Apparently, tools like maven add the java version to that, and when the local machine has a different java version than the one on another machine (i.e. the ci server), the match fails.

I'll take a look at that in my spare time, I hope someone had the same issue as me and he's already on it.

Many thanks,
Ale

**Comment by cowboygneox** [comment]
This is an excellent feature request, one that we will have to spend a little more time fleshing out. I don't think this will make the first 2.x release, but I think we can get to it before too long.

**Comment by cowboygneox** [comment]
Moved to Trello: https://trello.com/c/WR8IH4bR
