### ISSUE TITLE
regression testing of the REST services?

### ISSUE THREAD

**Issue by fommil** [betamaxteam/betamax#155]
(apologies, this is a question rather than a ticket)

It would be incredibly useful to be able to use betamax to record the inputs/outputs of an existing REST service and then use that to regression test the service in the future (with user adaption to allow custom equality at the xml/json level). Is that something one can use betamax for?

Also, are you tied to JSON/XML or do you support arbitrary payload types?

**Comment by restagner** [comment]
@fommil 

We have the exact same question for our purposes as that raised in this ticket. Considering it's been 2 months without a response, I'm going to assume that the answer is no.

**Comment by cowboygneox** [comment]
@fommil I have considered this as well, and I think it's an excellent feature suggestion. Will you reach out to me so we can discuss specifics?

**Comment by cowboygneox** [comment]
Also, we support arbitrary payload types.

**Comment by fommil** [comment]
I don't really have any specific usecase in mind at the moment, would just be useful in general

**Comment by cowboygneox** [comment]
It shouldn't be too hard to create a means that compares an outside source to a recorded interaction. I'll add it as a feature request.

**Comment by cowboygneox** [comment]
This is on Trello: https://trello.com/c/MEwtr6m2. Closing...
