### ISSUE TITLE
Default match rules are never used

### ISSUE THREAD

**Issue by mmazi** [betamaxteam/betamax#159]
`ProxyConfiguration.builder().defaultMatchRules()` has no effect. This is due to the fact that Recorder will _always_ use what it reads from `@Betamax(match)` since the latter can never be null (annotation element values can not be null in Java), and it would use default match rules only if it gets null from the annotation element (which is impossible).

This, together with #158, completely prevents the user from using custom rules.

(This is about the code in the current HEAD of the master branch.)

**Comment by cowboygneox** [comment]
@mmazi I have discovered this as well. We expose the ability to configure properties in too many places right now, so we'll have to take some out. My preference is to have it all driven in the test itself, but I feel others may like the `betamax.properties` as well. Your thoughts?

**Comment by mmazi** [comment]
@cowboygneox thanks for asking, but I'm not using BetaMax currently and I have no suggestions regarding this.

**Comment by cowboygneox** [comment]
@mmazi I'm going to close this. There will be plenty of conversation around configuration in this new reboot.
