### ISSUE TITLE
Link to example tape file on website is broken

### ISSUE THREAD

**Issue by thilko** [betamaxteam/betamax#164]
The link (Text place: "An example tape file can be found <here>."):

https://github.com/robfletcher/betamax/blob/master/src/test/resources/betamax/tapes/smoke_spec.yaml

on the Betamax page is broken.

**Comment by cowboygneox** [comment]
Thanks for submitting this. We're in the process of overhauling the documentation. Hopefully we'll have something exciting to show in March.
