### ISSUE TITLE
New release date ?

### ISSUE THREAD

**Issue by xSAVIKx** [betamaxteam/betamax#172]
Hi.
I think that your project is extremely helpful, so I want to ask when the new 2.* version of betamax will be released ? And what about maven central, are you planning to publish it there ?
And one more question: is releasing will take a while, should I use 1.* now and will it be easy to migrate from 1.* to 2.* in future ?

Thanks in advance for your answers :-)

**Comment by cowboygneox** [comment]
1. We will have a beta in March, but at the very minimum SNAPSHOTS. We've been refactoring and fixing a number of issues that are necessary in order for this library to be effective going forward.
2. [Bintray](https://bintray.com/bintray/jcenter) will be our primary deployment source (though we'll probably want to support others too).
3. We will have a migration guide of some sorts, but if you want something immediately, please use 1.1.2 and refactoring shouldn't be too hard in the future.
