### ISSUE TITLE
Filtering of sensitive data

### ISSUE THREAD

**Issue by xSAVIKx** [betamaxteam/betamax#173]
Hi.
I've tried to find any way to filter sensitive data (like API keys), but have no luck.
Do you have anything like Rubys [VCR sensitive data filtering](https://www.relishapp.com/vcr/vcr/docs/configuration/filter-sensitive-data) ?
If no, I think it's must-have feature :-)

**Comment by cowboygneox** [comment]
@xSAVIKx I agree we should come up with a way to do that, but is editing the tape not an option right now?

**Comment by xSAVIKx** [comment]
The problem is, that, for example, if you've got some API key that will be used in request query (like http://someurl/search?apiKey=someUniqueKey) it'll be saved in tape as it was requested and if you filter it on your own (just remove from tape) there won't be possibility to run this tape again without editing it again (to fill key).
As I understand, VCR have some filtering mechanism that allows to filter sensitive data before it's recorded as tape and restore sensitive data from somewhere (for example, from env variables) before it should be played.

**Comment by cowboygneox** [comment]
@xSAVIKx it seems reasonable to me that the tape should have some kind of variable syntax that you can supply. I will likely just reproduce what VCR did: https://www.relishapp.com/vcr/vcr/docs/configuration/filter-sensitive-data

**Comment by cowboygneox** [comment]
Moving to Trello: https://trello.com/c/WR8IH4bR
