### ISSUE TITLE
Allow users to configure authentication on the underlying proxy

### ISSUE THREAD

**Issue by pledbrook** [betamaxteam/betamax#174]
The underlying LittleProxy supports authentication through the _Proxy-Authentication_ and _Proxy-Authorization_ headers. You my wonder why this is relevant to Betamax. In my particular case, my project needs to support configurable proxies so that users can utilise my tool from behind a proxy. Since I'm already using Betamax in my integration tests, the proxy behaviour is also being tested.

One scenario that is not currently covered is the one involving authenticating proxies. I've fixed this in my tool, but I'd like to ensure it stays working with some tests. I could use LittleProxy myself, but then I'd have two proxies chained, whereas it would be easy to add a username & password to a Betamax recorder (I imagine).

I'll admit that it's doesn't exactly fit with Betamax's intended role, but I don't think such a convenience would be at all disastrous.

I plan to take a look at the Betamax code to see what might be involved in adding this feature.

**Comment by pledbrook** [comment]
From @robfletcher on Twitter:
> Betamax in many ways doesn’t behave like a real proxy. It might be a better bet to do it with LittleProxy directly

I'm including it here because Twitter's not the best medium for discussing these things :smile: I'm reluctant to run a whole other proxy and chain the two together simply to test whether the connection settings are handled correctly. That seems to be the cause of proxy-based issues, since the underlying behaviour of the proxy is handled by the JVM's networking stack.

As I see it, the feature could easily be implemented with one extra setting in `ProxyConfiguration` and a small change to `ProxyServer` that enables the proxy authenticator in the bootstrap class.

**Comment by pledbrook** [comment]
As a follow up to this, I managed to get my own LittleProxy instance running in front of Betamax, but it was a bit fiddly to ensure all the configuration was correct. I still think there might be value in adding this feature to Betamax, but it's not critical.

**Comment by cowboygneox** [comment]
@pledbrook I don't think this is asking for a lot, but I think it might have to wait for a bit for us to stabilize the existing 2.0 release. I would need your help to ensure that we can write some sort of test to capture this behavior. Any idea for how we can recreate this issue with an automated test?

**Comment by pledbrook** [comment]
[This test case from Lazybones](https://github.com/pledbrook/lazybones/commit/359c1f8b6ad1a3d51d0621105a21bf101508102d#diff-5b686fa89ece151982561f56cea76de5R14) may help. In addition, I was going to duplicate `IgnoreHostsSpec` in the _betamax-tests_ project. Testing this feature simply means starting the proxy server with a different configuration and verifying that 407 is returned when credentials are either not provided or incorrect.

I'll try to do something myself and send a pull request.

**Comment by pledbrook** [comment]
Hmmm...I see that the proxy system properties are overridden by `ProxyOverrider`. This isn't good for me because I'm running another proxy in front of Betamax. I imagine that my custom proxy will be bypassed if/when I upgrade to Betamax 2.

Should Betamax really be overriding the proxy settings if they're already set? I think at the very least, Betamax needs to provide an option to disable the automatic override.

**Comment by cowboygneox** [comment]
What I think we need to do is have LittleProxy proxy to the original proxy. Example: you set the proxy first, fire up Betamax, Betamax stores the original proxy settings (your settings), and then Betamax forwards to LittleProxy, which then forwards the request to the original proxy (your proxy). Does that make sense?

**Comment by pledbrook** [comment]
I think it's hard to know what those proxy settings might be for. I'm pretty sure I want my authenticating proxy to sit in front of Betamax. Betamax is there to imitate the remote HTTP server, so on that basis, I feel it should be at the end of the chain.

**Comment by cowboygneox** [comment]
@pledbrook Oh so I have the order backwards? Hmmm...I'll need to ponder that a bit... I guess that will ultimately mean that you'll have to fire up your proxy _after_ Betamax has started, so in a JUnit test, it will be after the @Rule has been made active.

**Comment by pledbrook** [comment]
Are you OK with moving this to a new issue? Although loosely connected to the enhancement I raised here, I think the proxy overrider deserves its own discussion/issue as something separate.

**Comment by cowboygneox** [comment]
@pledbrook Do I have the right understanding of your problem? If so, either you or I can make a feature request and explain the path forward.

**Comment by pledbrook** [comment]
@cowboygneox I'm not sure. I don't think the start order is relevant, except with regard to configuring the target port. The core issue is that Betamax overrides the client-side proxy settings. This is fine as long as the test wants requests to go through Betamax first, but it's a problem if those requests should hit a different proxy server first.

My expectation is that there will be no proxy configured in the vast majority of cases. In other cases, a functional test may have a firewall proxy configured to let that initial request hit the internet. Betamax should forward requests to this proxy for such scenarios. Finally, some rare tests will want to install a proxy in front of Betamax to log requests, verify authentication behaviour or otherwise do something with the requests before they hit Betamax.

I guess if we look at the problem like that, the least common option is probably the last one (although there's no data to back that up). In which case, the behaviour you suggested a little earlier is fine, where Betamax forwards the requests to whatever proxy is already configured. For the rare cases that this behaviour is undesirable, I think Betamax should have an option to disable the proxy overrider so that the proxies can be manually linked together in whichever way the test needs.

**Comment by pledbrook** [comment]
As an addendum, it appears there's already a test for already configured proxies: `PreExistingProxySpec`.

**Comment by cowboygneox** [comment]
@pledbrook I'm going to move the conversation into another issue like you suggested.

**Comment by cowboygneox** [comment]
Closing this because @pledbrook's merge request to address this issue was merged.
