### ISSUE TITLE
Allow a configured proxy to come before Betamax's proxy

### ISSUE THREAD

**Issue by cowboygneox** [betamaxteam/betamax#182]
Conversation began on https://github.com/betamaxteam/betamax/issues/174.

If I'm capturing @pledbrook's request, he requests that we offer an additional capability to allow configuration of the Betamax proxy after an existing proxy, rather than before (which is the current functionality).

**Comment by cowboygneox** [comment]
@pledbrook I see your argument that the proxy should come first prior to Betamax since Betamax is supposed to be a MITM for the "remote server". However, I'm wondering if the order is irrelevant? It could be argued that Betamax is just the first hop, not the last one, but even so, it creates the same interaction either way. Can you help me understand what difference we would see in behavior if the order were reversed from the existing?

**Comment by pledbrook** [comment]
@cowboygneox My understanding is that Betamax is a effectively a terminal proxy when in replay mode. Any proxies after Betamax will see the first request, but no subsequent ones. I'm not even sure that Betamax can record and replay the challenge/response for proxy authentication. I can't imagine it working with my current setup if the dedicated authenticating proxy were to come after Betamax.

More generally, a user may want to put a proxy in front that intercepts every request, even when Betamax is in replay mode, whether that be for special logging or report output or whatever. How would that work if the proxy came after Betamax?

**Comment by cowboygneox** [comment]
@pledbrook I'm failing to understand why you can't set your proxy first in the system properties, and then enable Betamax. Won't that create the desired effect?

**Comment by pledbrook** [comment]
I doubt it, as Betamax overrides those system properties. When I have a moment, I'll give the beta release a try in case it does work. Even if that were the case, I'm not in favour of Betamax replacing those properties without some way for the user to disable or otherwise control that behaviour.

**Comment by cowboygneox** [comment]
@pledbrook Yes but you can override them _after_ Betamax does too, can't you? You just have to make sure your proxy points at Betamax.

**Comment by pledbrook** [comment]
@cowboygneox This is proving difficult to test because I no longer reliably have access to the Betamax proxy settings (available via `recorder.proxy.address` in the 1.x series). I could force the Betamax proxy to run on a particular host and port, but then I run into potential port conflicts.

In addition, I don't see how one can reliably determine the order that rules and test setup methods run in, without knowing more than one should have to about how JUnit works.

**Comment by pledbrook** [comment]
OK, I have tested this, although it relies heavily on the order that my `setup()` method runs relative to the `RecorderRule`. I don't know if JUnit behaves the same as Spock in this regard.

Anyway, this does work as `setup()` runs after the Betamax proxy server starts, so I can read the proxy settings from the corresponding system properties and override them myself. It's a bit ugly, but I don't know whether it's possible to expose the `ProxyServer` settings in a clean way. Definitely something to consider, though.

**Comment by cowboygneox** [comment]
Moved to Trello: https://trello.com/c/Q3EDxiv2.
