### ISSUE TITLE
Configuration.defaultMode is not honoured in 2.0.0-alpha1

### ISSUE THREAD

**Issue by ysb33r** [betamaxteam/betamax#184]
I was just trying out the 2.0.0-alpha1 today and I suspect `Configuration.defaultMode` is not honoured.

Here is is some stripped down code from a Spock test

``` groovy
@Shared ProxyConfiguration configuration = ProxyConfiguration.builder().
        defaultMode( TapeMode.READ_WRITE   ).
        build()

@Betamax(tape='foo')
def "My test"() {
}
```

That always fails with a `tape is read-only` error.

**Comment by ysb33r** [comment]
I speak under correction, but I think this is the issue.

In the `Betamax` annotation, the default for mode is [READ_ONLY](https://github.com/betamaxteam/betamax/blob/master/betamax-junit/src/main/java/software/betamax/junit/Betamax.java#L33).

hen in the [RecorderRule](https://github.com/betamaxteam/betamax/blob/master/betamax-junit/src/main/java/software/betamax/junit/RecorderRule.java#L62), the annotation value is assigned and passed through to the `start(tapeName, tapeMode, matchRule)`.

This ends up calling a [Recorder.start method](https://github.com/betamaxteam/betamax/blob/master/betamax-core/src/main/java/software/betamax/Recorder.java#L69), which eventually ends up execyting the line `tape.setMode(mode.or(configuration.getDefaultMode()))`. As the mode is already set `mode.or` will never be called.

**Comment by cowboygneox** [comment]
I'll look at this over the weekend. I wasn't surprised that this may be an issue. Thanks for letting us know!

**Comment by pledbrook** [comment]
I suspect this is a problem with the match rules too. The global and recorder configurations will never kick  in, as you always(?) have a `Betamax` annotation. I'm not sure that any of the annotation's fields should have default values.

**Comment by cowboygneox** [comment]
@pledbrook @ysb33r The many different ways to set the tapeMode is a problem anyway. There should be a `running` configuration (which almost always is READ_ONLY), and then there is a `writing test` configuration, which probably should be overwritten via java properties and _not_ checked into git. That way, a developer is free to write, but CI will enforce that the proper tape is checked in. Thoughts?

**Comment by cowboygneox** [comment]
In the mean time, I'll see if I can fix this with something quick and put it into the SNAPSHOT.

**Comment by pledbrook** [comment]
I like the idea, but I think this can be simplified to:

* Default behaviour is `READ_ONLY`
* The other modes remain configurable via existing mechanisms (`ProxyConfiguration` and `@Betamax`)
* A `betamax.allow.write` or similar system property automatically overrides `READ_ONLY/SEQUENTIAL` to the corresponding write versions. It ignores any tests that are already marked as write.

The only difference from the existing behaviour is the last step.

**Comment by cowboygneox** [comment]
@pledbrook I think we're generally in alignment. I just have to come up with an optional scheme that makes me happy, which may be the real challenge here since I prefer Scala over Java.

**Comment by ysb33r** [comment]
To paraphrase @pledbrook

* If nothing is set the `READ_ONLY`
* If a default is set via `ProxyConfiguration` then that becomes the default
* If a value is set via `@betamax`, then that would override any of the previous two
* System property beats all.

I'm good with that.

> I prefer Scala over Java

I think most JVM people nowadays prefers another JVM langiage over Java :-)  Anyhow that is besides the point. I think if you need to find something that also works for Scala that cal also slot into the above list somewhere then do that.

**Comment by cowboygneox** [comment]
Moving this into Trello: https://trello.com/c/qyTUkX75.
