### ISSUE TITLE
Missing Java7 support

### ISSUE THREAD

**Issue by xSAVIKx** [betamaxteam/betamax#185]
Hi.
I've noticed, that you're uploading archives from java8 build, but that gets to Unsupported java version:

> Unsupported major.minor version 52.0

Like I've received during my tests for Java7 jdks: [travis-ci build](https://travis-ci.org/xSAVIKx/twingly-search-api-java/jobs/115517111)

Could you please publish release compiled with Java7, so that it could be run on java7 (as well as on java8) ?

**Comment by xSAVIKx** [comment]
Closed with #186

**Comment by cowboygneox** [comment]
@xSAVIKx Thanks for closing this.
