### ISSUE TITLE
`TapeMode.READ_ONLY` seems to have no effect

### ISSUE THREAD

**Issue by pledbrook** [betamaxteam/betamax#188]
When I change the tape mode to READ_ONLY, unknown requests still go through to the target server. The problem seems to be in [`BetamaxFilters`](https://github.com/betamaxteam/betamax/blob/master/betamax-core/src/main/java/software/betamax/proxy/BetamaxFilters.java#L139), which only returns a 403 if there is no tape specified for the test. I'd argue that `onRequestIntercepted()` needs to check whether the tape is writable before forwarding the request.

On a side note, there is a test for read-only behaviour, but it's currently skipped due to an `@Ignore` annotation :open_mouth:

**Comment by pledbrook** [comment]
I'm not sure what the behaviour should be here. The user guide says that Betamax returns a 403 response, but the test checks for a `NonWritableTapeException`.

**Comment by cowboygneox** [comment]
@pledbrook Anytime I turn off a test, I get burned. This is something I've been aware of and have been trying to address, but upgrading littleproxy has fixed many things, but has broken this. However, fixing this shouldn't be that hard of a problem. If you have some time to fix the ignored test, that would help me a lot.

**Comment by pledbrook** [comment]
@cowboygneox I would help, but I need to know what the required behaviour is :smile: I favour the behaviour described in the user guide, but we need to agree on that.

**Comment by cowboygneox** [comment]
@pledbrook I'll take a look and fix it.

**Comment by engeliii23** [comment]
any updates regarding this issue?

**Comment by cowboygneox** [comment]
@engeliii23 I haven't had a lot of time for Betamax as of late. Is this blocking you in some way?

**Comment by thomashunziker** [comment]
Is there any update on the issue? It blocks us a bit, because we use a CI server. When the remote API is offline we are unable to create a new release.

**Comment by cowboygneox** [comment]
@thomashunziker I've been struggling to find time for this project lately. However, I know that there are currently functional options for making Betamax run without access to a remote API. Could you make a separate issue?

**Comment by thomashunziker** [comment]
If you point me out where I should look into I can eventually help fixing the issue.

**Comment by cowboygneox** [comment]
@thomashunziker Ping me via Gitter or email.

**Comment by cowboygneox** [comment]
Moving to Trello: https://trello.com/c/qyTUkX75.
