### ISSUE TITLE
Writeup detailed documentation on how to use SSL testing

### ISSUE THREAD

**Issue by cowboygneox** [betamaxteam/betamax#190]
Even I am struggling to get it to be straight forward, so a good walk through on http://betamax.software would be a much needed addition.

**Comment by pledbrook** [comment]
I'd be interested to hear from @robfletcher what, if anything, has changed here. It seemed to work fine with 1.x.

**Comment by cowboygneox** [comment]
IMO, the 1.x documentation didn't appropriately cover non-supported clients, plus we didn't use littleproxy, so it's changed a lot since then.

**Comment by pledbrook** [comment]
It may not have been clear, but I was really just wondering whether it's intentional that 2.x doesn't seem to be a drop-in replacement for 1.x as far as the SSL support goes (see #189). I would always :+1: improvements to the docs!

**Comment by cowboygneox** [comment]
I'm closing this as the SSL support is now documented in the README.
