### ISSUE TITLE
Add upgrade notes for 1.x -> 2

### ISSUE THREAD

**Issue by pledbrook** [betamaxteam/betamax#191]
These are the things I've noticed so far:
- Add `betamax-junit` as a dependency if using `@Betamax` and `@Rule`
- Update import packages
- Replace `Recorder` with `RecorderRule` (if using rules)
- `Recorder.getProxy()` is no longer available - you'll need to  read the proxy settings from the standard JVM proxy system properties (Betamax sets these when it starts the proxy recorder)
- BetamaxConfig.groovy i no longer used - switch to _betamax.properties_
- The `betamax.sslSupport` configuration option has been changed to `betamax.sslEnabled`

**Comment by helpermethod** [comment]
Thanks, that really helped :).

**Comment by mabn** [comment]
MatchRule.headers has been removed. There is no longer a way to match on all headers using `@Betamax` annotation. The only workaround I found is to use `Configuration.defaultMatchRule` and implement own `MatchRule`.

**Comment by cowboygneox** [comment]
Moved this to our Documentation Trello Card: https://trello.com/c/9jdBEGaR
