### ISSUE TITLE
'Reconcile' mode (matching live requests to stored tape)

### ISSUE THREAD

**Issue by adamdecaf** [betamaxteam/betamax#195]
We've forked betamax and came up with a new tape mode. It's called '[Reconcile](https://github.com/Banno/betamax#new-tape-mode-reconcile)' to be able to run the live requests but then match against the tape and fail only when the new response doesn't match up with the stored response. It's a bit easier to use day-to-day than to re-build the entire tape nightly or not. 

We have a [diff of all of our changes](https://github.com/betamaxteam/betamax/compare/master...Banno:banno) on the Banno fork.

**Comment by cowboygneox** [comment]
@adamdecaf Small world, man. Do you mind making a pull request?

**Comment by cowboygneox** [comment]
@adamdecaf I'm pretty sure that your fork has diverged quite a bit from master. It appears that most of your work has been against the 1.1.2 branch, not the 2.0. Perhaps we should come up with a plan to get 'Reconcile' working on the 2.0 master?

**Comment by adamdecaf** [comment]
Yea. We can see how that will look. I need to read over the 2.0 source to get a better idea

**Comment by cowboygneox** [comment]
Moving this to Trello: https://trello.com/c/MEwtr6m2.
