### ISSUE TITLE
query matchrule

### ISSUE THREAD

**Issue by auhlig** [betamaxteam/betamax#206]
The current set of match rules allows only to check for string equality. This causes a problem in the uri's query when the query is semantically identical but due to a different order of the parameters the string representation is not.
For example:
```http://freeside.co/betamax?p=2&q=1```vs ```http://freeside.co/betamax?q=1&p=2```.

I follow up with a PR to address the previously described issue.

**Comment by gondor** [comment]
+1 +1

**Comment by cowboygneox** [comment]
#207 was merged. Closing...
