### ISSUE TITLE
Fix GZIP support

### ISSUE THREAD

**Issue by cowboygneox** [betamaxteam/betamax#216]
GZIP creates a conflict of interest in our tapes where we want the tape to be editable, but also compressed. Really, we should just remove `Content-Length` from the persisted payload and just infer it based on the tape's payload. I thought I already did this, but it's still not working, so I'll have to fix it.

**Comment by solvingJ** [comment]
+! Thanks!

**Comment by cowboygneox** [comment]
Moving this to Trello: https://trello.com/c/qlor2w70.
