### ISSUE TITLE
Stale Tapes - OAuth Token Expiration - Possible Solution?

### ISSUE THREAD

**Issue by solvingJ** [betamaxteam/betamax#217]
Note: This problem seems to affect VCR as well, don't know if they ever resolved: 

https://www.relaxdiego.com/2013/06/mocking-web-services-with-vcr.html

Problem:  Some (perhaps all) OAuth/OAuth2 tokens have actual "expires_on" values that some (perhaps all) HTTP clients honor.  Once this date has passed, the tape will no longer playback properly.  Clients detect that the token is expired, and request a refresh. Even if you record the refresh, it will have an "expires_on" date as well. 

I've done some work with OAuth, but not enough to know the gory detail of how clients process the tokens.  I'm not sure if this will work, but if it does work, it COULD be relatively easy (with respect to the scope of the problem). 

Proposed Solution: 
On playback, Betamax identifies oauth responses and modifies the "expires_on" field to be some stamp in the distant future.  Perhaps the other fields will also need modding, but this seems like the one to start with.  If the access token includes the "expires_on" field in it's hash algorithm, this won't work. 

It's possible that all such OAuth2 requests would have a URL ending with exactly 'oauth2/token'

Even if it works, not sure how much variety there is between OAuth1 and 2, or other security mechanisms that might be out there.  Still, I think OAuth2 is common enough to start with. 

Here is the JSON body from an OAuth2 "response" from one of my tapes: 
body: `{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"10800","expires_on":"1473801040","not_before":"1473797140","resource":"https://website.com/","access_token":"TokenHashValue"}`

**Comment by solvingJ** [comment]
As a side note, I manually changed the "expires_on" value on one of my expired tapes, and it seemed to have no effect. I expected a different error.  Hopefully someone else can do the same test and validate my result.

**Comment by cowboygneox** [comment]
I'll need some time to consider this issue. It initially seems difficult to MITM the OAuth information due to its many number of implementations. Normally an OAuth token generator allows the option to create an indefinite token, but I guess not always.

**Comment by cowboygneox** [comment]
@solvingJ Is your application actually validating the OAuth token?

**Comment by solvingJ** [comment]
I'm using the OkHTTP3 library and it seems to be automatically validates the OAuth token.

**Comment by cowboygneox** [comment]
Combining this with our ability to filter tapes request: https://trello.com/c/WR8IH4bR.

**Comment by relaxdiego** [comment]
Sorry for reviving this old issue but thought I'd share how I get around to time-sensitive tapes in case it helps: I use TimeCop to "reverse" the time to the date and time that the cassette was recorded on. This happens automatically at test time by having my test infrastructure inspect the creation date of the cassette, call TimeCop to reverse the time, then bring the time Back to The Future (heh, sorry. couldn't resist!) after the test is done.
