### ISSUE TITLE
betamax doesn't creates tapes

### ISSUE THREAD

**Issue by spilth** [betamaxteam/betamax#218]
When I run my test:

- `src/test/resources/betamax/tapes` (the default tape directory) is not created
- no tapes are made.

I'm using https and have added the `betamax.pem` using `keytool`.

Here's what's in my `pom.xml`:

    <dependency>
        <groupId>software.betamax</groupId>
        <artifactId>betamax-junit</artifactId>
        <version>2.0.1</version>
        <scope>test</scope>
    </dependency>
    
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpclient</artifactId>
        <version>4.5.1</version>
    </dependency>
        
And here's what my test looks like:

    public class ContentAPITest {
        @Rule
        public TestName testName = new TestName();

        @Rule
        public ExpectedException thrown = ExpectedException.none();

        Configuration configuration = Configuration.builder().build();
        @Rule
        public RecorderRule recorder = new RecorderRule(configuration);
        
        private ContentAPI api;

        @Before
        public void before() throws ContentAPIException {
            api = new ContentAPI(
                    System.getenv("LIOX_API_ACCESS_KEY_ID"),
                    System.getenv("LIOX_API_SECRET_KEY"),
                    System.getenv("LIOX_API_ENDPOINT"),
                    System.getenv("LIOX_API_DEFAULT_CURRENCY")
            );
        }
    
        @Test
        public void listLocales_returnsLocalesList() throws ContentAPIException {
            List<Locale> locales = api.listLocales().getLocales();

            assertThat(locales, Matchers.<Locale>hasItem(hasProperty("name", equalTo("English (United States)"))));
            assertThat(locales, Matchers.<Locale>hasItem(hasProperty("code", equalTo("en-us"))));
        }   
    }
    
ContentAPI.listLocales uses `org.apache.httpcomponents:httpclient:4.5.1` to contact a REST API and retrieve a list of Locales.

**Comment by cowboygneox** [comment]
This is almost always an issue with Betamax not being hit by the http client. Are you positive that Betamax is correctly setup as a MITM?

**Comment by cowboygneox** [comment]
I don't see the test being annotated with `@Betamax`?

**Comment by quiqua** [comment]
I am kinda stuck at the same point:

```
package io.tests.vcr;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;
import org.junit.Rule;
import org.junit.Test;
import software.betamax.Configuration;
import software.betamax.junit.Betamax;
import software.betamax.junit.RecorderRule;

import java.io.File;

public class MyTest {

    File tapes = new File("src/test/resources/betamax/tapes");
    Configuration configuration = Configuration.builder()
            .tapeRoot(tapes)
            .ignoreLocalhost(false)
            .sslEnabled(true)
            .build();

    @Rule
    public RecorderRule recorder = new RecorderRule(configuration);

    @Test
    @Betamax
    public void shouldRecordSomething() throws Exception {
        HttpClient client = HttpClientBuilder.create().build();
        HttpGet request = new HttpGet("http://google.com");

// add request header
        HttpResponse response = client.execute(request);
    }
}
```
I can see in the logs that the proxy gets started and the folder is created, but no file will be recorded.

Are there any more hints regarding the interaction with a `HTTPClient` and `Betamax`?

**Comment by cowboygneox** [comment]
I'm not sure what happens if you don't name the tape. Can you try naming it?

**Comment by quiqua** [comment]
`@Betamax(tape = "myFirstRecord")` doesn't change it. It should get the use the method name, if no name is defined: https://github.com/betamaxteam/betamax/blob/master/betamax-junit/src/main/java/software/betamax/junit/RecorderRule.java#L59-L61

What about: https://github.com/betamaxteam/betamax/blob/master/betamax-junit/src/main/java/software/betamax/junit/Betamax.java#L33-L35? (Just some wild guessing here)

**Comment by cowboygneox** [comment]
@quiqua It's most likely that your http client needs to be specifically configured to use a proxy. Some clients use the JVM's configured proxy, but many don't. Can you try manually configuring the client to point at localhost on Betamax's port and see if that resolves the issue?

**Comment by cowboygneox** [comment]
Related to #221, be sure you're setting the `TAPE_MODE` to `READ_WRITE` in `@Betamax`.

**Comment by quiqua** [comment]
@cowboygneox Thanks for your input.

When using `org.apache.http.client.HttpClient` one has to set the proxy via the builder explicitly or specify to use _SystemProperties_:

```
// explicit: 
HttpClient client = HttpClientBuilder.create().setProxy(HttpHost.create("0.0.0.0:5555")).build();

// pass JVM args: -Dhttp.proxyHost=0.0.0.0 -Dhttp.proxyPort=5555
HttpClient client = HttpClientBuilder.create().useSystemProperties().build()
```

**Comment by cowboygneox** [comment]
@quiqua did that solve your problem? Presumably, `useSystemProperties()` should work with Betamax.

**Comment by quiqua** [comment]
Yes, both options listed there work.

**Comment by cowboygneox** [comment]
@spilth Can we close this? I will be sure to improve this confusion in the documentation that I need to do (because it's way overdue and I'm slacking).

**Comment by spilth** [comment]
@cowboygneox Sure. I haven't gotten a chance to try it myself but it sounds like it's working for @quiqua . Ultimately I'd like to help out with the documentation piece of this but I've only gotten as far as Forking the betamax website project 😬 

@quiqua Can you share your full working code?

**Comment by cowboygneox** [comment]
@spilth I would love help, but we have to start from scratch. The existing docs for 1.x are very different than what's required for 2.x. Let me know if you want to coordinate.

**Comment by spilth** [comment]
@cowboygneox Perhaps I'll start with a tutorial on my own site and you can lift what you'd like from there. I'm shooting for a straightforward, getting up and running with Maven type tutorial that shows the simplest way to use Betamax.

**Comment by cowboygneox** [comment]
Perfect. I really appreciate the help!

**Comment by quiqua** [comment]
@spilth 

```java
package io.tests.vcr;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;
import org.junit.Rule;
import org.junit.Test;
import software.betamax.Configuration;
import software.betamax.TapeMode;
import software.betamax.junit.Betamax;
import software.betamax.junit.RecorderRule;

import java.io.File;

public class MyTest {

    File tapes = new File("src/test/resources/betamax/tapes");
    Configuration configuration = Configuration.builder()
            .defaultMode(TapeMode.READ_WRITE)
            .tapeRoot(tapes)
            .ignoreLocalhost(false)
            .sslEnabled(true)
            .build();

    @Rule
    public RecorderRule recorder = new RecorderRule(configuration);

    @Test
    @Betamax
    public void shouldRecordSomething() throws Exception {
        HttpClient client = HttpClientBuilder.create()
            .setProxy(HttpHost.create("0.0.0.0:5555"))
            // OR
            //.useSystemProperties() 
            .build();
        HttpGet request = new HttpGet("http://google.com");

        HttpResponse response = client.execute(request);
    }
}
```

If the latter is used, `-Dhttp.proxyHost=0.0.0.0 -Dhttp.proxyPort=5555` must be passed to the JVM.

**Comment by spilth** [comment]
In my attempt to come up with the minimal example, here's what I came up with:

- https://github.com/spilth/betamax-example/blob/master/src/test/java/spilth/org/AddressFinderTest.java
- https://github.com/spilth/betamax-example/blob/master/src/main/java/spilth/org/AddressFinder.java
