### ISSUE TITLE
can we modify outgoing responses dynamically?

### ISSUE THREAD

**Issue by babarismail** [betamaxteam/betamax#222]
Say a test sends a different id to the server every time. I can write a custom matching rule that will ignore that id to match the response, but is there a way to update that id in the mocked response or will it always return exactly what's in the yaml?

**Comment by cowboygneox** [comment]
Replaying tapes is a static process. However, I would consider a feature request to make some parameters variable, perhaps through environment variables or some templating scheme. Thoughts?

**Comment by babarismail** [comment]
I have a code change that is based upon the MatchingRule concept. I added an interface called ModifyRule that gets setup just like a matching rule in the config. Before the response is returned, the modify rule is applied on the outgoing response.
I really like this concept since it gives freedom to the framework user to write any modification logic as opposed to following a given template.

**Comment by cowboygneox** [comment]
@babarismail I look forward to seeing the patch. It sounds awesome!

**Comment by cowboygneox** [comment]
Moved to Trello: https://trello.com/c/WR8IH4bR
