### ISSUE TITLE
OkHttp support

### ISSUE THREAD

**Issue by felipecsl** [betamaxteam/betamax#240]
[OkHttp](https://github.com/square/okhttp) is a very popular http client, especially on Android.
I'd like to use Betamax to record/replay network interactions that go through OkHttp for integration tests that run on an Android device or emulator so they are more consistent and repeatable.
I understand that Betamax as is doesn't work with OkHttp so I've forked Betamax and started working on the changes to make it possible.
It would basically work as a [Interceptor](https://github.com/square/okhttp/wiki/Interceptors) that records/plays from the Tape using the same rules that exist on Betamax today.
Is this something you guys would consider taking as an open source contribution? Since there are quite a lot of differences, i'd keep it as a separate repository/artifact, maybe something like `betamax-interceptor`. How does that sound?
Thank for sharing this awesome tool!

**Comment by quiqua** [comment]
I'd love to see that in Betamax, I started using OkHttp + Betamax quite recently as well, recording tapes in alright, but you ran into issues when you need to play back a recorded body.
So your solutions sounds nice :)

**Comment by felipecsl** [comment]
I have the work underway in a branch, working on fixing the failing unit tests now (thanks a lot for writing them 😄 ), will share when I have it in a working state

**Comment by felipecsl** [comment]
The code is now (temporarily) lives here https://github.com/felipecsl/walkman
It's currently alpha stability but feel free to use and send feedback 😃

**Comment by felipecsl** [comment]
Ok this has been officially open sourced as https://github.com/airbnb/okreplay
