### ISSUE TITLE
Proxy should return a custom HTTP status

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#71]
Currently the proxy returns various HTTP statuses but the potential exists for them to conflict with expected statuses in tests. For example the proxy will return _403 FORBIDDEN_ if the tape is not writable and there is no existing recording that matches the request. If the test was actually expecting _403 FORBIDDEN_ because it's checking authentication then this could cause unnecessary confusion.

Problems connecting to the target _are_ handled appropriately but the various expectation failures (no tape, tape is not writable, etc.) should use a custom _4xx_ HTTP code (or possibly multiple such codes).

**Comment by cowboygneox** [comment]
Moved to Trello: https://trello.com/c/GGBtvEAv
