### ISSUE TITLE
Proxy times out when using more than one @Betamax annotated test method in a test class

### ISSUE THREAD

**Issue by pfeff** [betamaxteam/betamax#77]
If you have a Java project that calls a SOAP service and has more than one @Betamax annotated tests in the same class, the second request will timeout.

I created a test project to demonstrate: https://github.com/pfeff/betamax-demo

Betamax Version: 1.1.2
$ java -version
java version "1.6.0_24"
OpenJDK Runtime Environment (IcedTea6 1.11.8) (rhel-1.35.1.11.8.el5_9-x86_64)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)

**Comment by cowboygneox** [comment]
Are the tests running in parallel?

**Comment by cowboygneox** [comment]
I apologize, but we are no longer supporting Betamax 1.x. Closing...
