### ISSUE TITLE
Documentation tasks in Gradle build don't compile stylesheet

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#88]
Right now it's necessary to manually recompile the stylesheet before building the docs. Would be nice to use the robfletcher/gradle-compass plugin to automate this. That will mean porting the docs to Sass but that should be easy enough.

**Comment by cowboygneox** [comment]
I'll add this as a consideration to the documentation story on Trello: https://trello.com/c/9jdBEGaR
