### ISSUE TITLE
Support a standalone proxy mode

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#89]
Currently Betamax is very closely coupled to the JUnit @Rule mechanism. This is fine for JUnit & Spock users but not for TestNG, ScalaTest, etc. Although it's possible to start up the proxy programmatically it's not very convenient. It's also a bit of a code smell that the Recorder class is at once the central entry point for the Betamax API and the JUnit rule implementation. It would make sense to separate the two concepts.

**Comment by cowboygneox** [comment]
Moving to Trello: https://trello.com/c/MEwtr6m2
