### ISSUE TITLE
Allow a predicate to determine if a response gets saved

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#91]
Particularly useful for tests that hoover down HTML pages where you may want to exclude images or other static resources from the tape.

**Comment by cowboygneox** [comment]
I disagree with this. If we have *some* resources that are not consistent with the snapshot of others, it can and will create a timebomb that will ultimately blow up in the developers face in the future. Please feel free to reopen this if you would like to discuss further.
