### ISSUE TITLE
It is not recording when i create my own jar using the betamax source code

### ISSUE THREAD

**Issue by prassan86** [betamaxteam/betamax#95]
Hi,

I have created a sample project and tested it with betamax jar. It was recording the web request and response . But when i create a jar using the Betamax source code it was not recording the request . I was trying to analyze the flow of the betamax source . Please help.

**Comment by cowboygneox** [comment]
I hope that you eventually got this working. Since we no longer support 1.x, I'm closing this. Please file another issue if you are still having problems with 2.x.
